#pragma once

#define SIA_TARGET_UNDEFINED 0
#define SAI_TARGET_MD 1
#define SAI_TARGET_C1 2
#define SAI_TARGET_C2 3
#define SAI_TARGET_SYS16B 4
#define SAI_TARGET_SYS18 5
#define SAI_TARGET_CPS 6
#define SAI_TARGET_CPS2 7
