//
// Saikodev Neo-Geo memory card functions and enums.
//

#pragma once

#include "sai/neogeo/hw.h"
#include "sai/macro.h"
#include "sai/sysrom.h"

// Memory card function commands
SAI_ENUMSTART
SAI_ENUMNEXT(CARD_COM_FORMAT)
SAI_ENUMNEXT(CARD_COM_SEARCH)
SAI_ENUMNEXT(CARD_COM_LOAD)
SAI_ENUMNEXT(CARD_COM_SAVE)
SAI_ENUMNEXT(CARD_COM_DELETE)
SAI_ENUMNEXT(CARD_COM_TITLE)
SAI_ENUMNEXT(CARD_COM_USERNAME_SAVE)
SAI_ENUMNEXT(CARD_COM_USERNAME_LOAD)
SAI_ENUMNEXT(CARD_COM_COUNT)
SAI_ENUMEND

// Memory card command answers
SAI_ENUMSTART
SAI_ENUMNEXT(CARD_ANS_OK)
SAI_ENUMNEXT(CARD_ANS_INSERT_ERR)
SAI_ENUMNEXT(CARD_ANS_FORMAT_ERR)
SAI_ENUMNEXT(CARD_ANS_NODATA)
SAI_ENUMNEXT(CARD_ANS_FAT_ERR)
SAI_ENUMNEXT(CARD_ANS_DATA_FULL)
SAI_ENUMNEXT(CARD_ANS_READ_ONLY)
SAI_ENUMNEXT(CARD_ANS_COUNT)
SAI_ENUMEND

//
// Card function macros / wrappers
//

// TODO

#ifndef __ASSEMBLER__

#else

#endif  // __ASSEMBLER__
